services:
  db:
    image: mysql:8.0
    container_name: movie_booking_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: priyansh
      MYSQL_DATABASE: movie_ticketing
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: movie_booking_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: priyansh
      DB_NAME: movie_ticketing
    command: node app.js
    volumes:
      - .:/usr/src/app

volumes:
  db_data:
